version: "3.8"
services:
    db:
        image: postgres:16
        environment:
            POSTGRES_DB: lms-be
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        volumes:
            - lms-be:/var/lib/postgresql/data
        restart: always

volumes:
    lms-be:
