name: Development CI/CD Pipeline

on:
    push:
        branches:
            - development

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.20'

            - name: Test
              run: go test -v ./...

            - name: Build
              run: go build -o main .
            
            - name: Archive Build Output
              run: tar -czvf main.tar.gz main

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: build-artifact
                path: main.tar.gz

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: development
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Download Build Artifact
              uses: actions/download-artifact@v3
              with:
                name: build-artifact

            - name: Deploy to Development Environment
              env:
                  VPS_IP: ${{ secrets.VPS_IP }}
                  VPS_USER: ${{ secrets.VPS_USER }}
                  VPS_KEY: ${{ secrets.VPS_KEY }}
              run: |
                  echo "$VPS_KEY" > vps_key.pem

                  chmod 600 vps_key.pem

                  scp -o StrictHostKeyChecking=no -i vps_key.pem main.tar.gz $VPS_USER@$VPS_IP:/home/hmcroot/app/development/lms-be/
                  ssh -o StrictHostKeyChecking=no -i vps_key.pem $VPS_USER@$VPS_IP "
                  cd /home/hmcroot/app/development/lms-be &&
                  rm -f main &&
                  tar -xzvf main.tar.gz && rm -f main.tar.gz
                  sudo systemctl restart lms-be-development.service"
